# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches:
    - '/**'
    - master
  pull_request:
    branches:
    - master

jobs:
  runner-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      redis:
        image: redis
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db
        ports:
          - 3306:3306
      elasticsearch:
        image: elasticsearch:7.14.1
        ports:
          - 9200:9200
          - 9300:9300
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        env:
          discovery.type: single-node
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Cat
        run: cat /etc/hosts
      - name: Append raw.githubcontent.com
        run: |
          echo 185.199.111.133 raw.githubusercontent.com >> /etc/hosts
          echo 185.199.110.133 raw.githubusercontent.com >> /etc/hosts
          echo 185.199.109.133 raw.githubusercontent.com >> /etc/hosts
          echo 185.199.108.133 raw.githubusercontent.com >> /etc/hosts
      - name: Prepare elasticsearch data
        run: |
          wget https://raw.githubusercontent.com/zq2599/blog_demos/master/files/create_shakespeare_index.sh
          chmod a+x create_shakespeare_index.sh
          ./create_shakespeare_index.sh 127.0.0.1 9200
          ./create_shakespeare_index.sh elasticsearch 9200
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
        env:
          SPRING_REDIS_HOST: redis
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db
          SPRING_ELASTICSEARCH_REST_URIS: elasticsearch:9200
